import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import styles from '@/styles/Home.module.css'
import Block from '@/components/Block'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [dataa,setData] = useState(null);
  const [submitsState, setSubmitState] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  // function min(){
  //   alert("Added to queue check back in 5min")
  //   document.getElementById("formm").reset()
  // }
  function final(Data){
    console.log(Data);
    var d = Data.data;
    var arr=[];
    for(var i=0;i<d.length;i++){
      if(d[i].length>1){
        arr.push(JSON.parse(d[i]))
      }
    }
    setData(arr)
    console.log(dataa);
    setIsLoading(false);
    setSubmitState(true);
    
  }
  function submitForm(){
    setIsLoading(true)
    var url = document.getElementById("search").value;
    fetch("/api/hello", {
      method: "POST",
      body: url
    })
      .then((response) => response.json())
      .then((data) => final(data)
      )
      .catch((error) => console.error(error))

  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {isLoading ? (
        <p>Loading...</p>
      ) : (<>
        <div className={styles.h1box}>
          <h1 className="h1">Securify</h1>
        </div>
        <div className={styles.topnav}>
          <form id="formm" onSubmit={(event) => {
    event.preventDefault(); // prevent default form submission behavior
    submitForm(); // call submitForm function
  }}>
          <input className={styles.searchbox} id="search" type="text" placeholder='Search'/>
        <img onClick={(event) => {
    event.preventDefault(); // prevent default form submission behavior
    submitForm(); // call submitForm function
  }}  className={styles.icon} src="https://i.postimg.cc/NG5CFrdK/image.png"/></form></div>
  <div className="margin-top">
  {submitsState && <Block data={dataa} />}
  </div></>)}


        {/* <p>as{data}</p> */}
      </main>
    </>
  )
}
